### ISSUE TITLE
failed to load the recommendations-40.dump with error 'Not a valid Neo4j archive'

### ISSUE THREAD

**Issue by dollyk** [neo4j-graph-examples/recommendations#8]
Hi Sirs,
I am trying to build the recommendation database at local by loading the given dump file: `recommendations-40.dump`, but get the `Not a valid Neo4j archive`  error  (same error both on windows and ubuntu)   

Besides, I also surveyed and tried the possible solution about the error  [Knowledge Base neo4j-admin load causes "Not a valid Neo4j archive"](https://neo4j.com/developer/kb/neo4j-admin-load-causes-not-a-valid-neo4j-archive/#_fix_workaround),  but is still got same error.

Is there another limitation about the dumped file? or Is there any idea or suggestion about this?

- neo4j: 4.0.7
- with terminal from Neo4j Desktop on Windows
    ```
    .\bin\neo4j-admin load --from data\recommendations-40.dump --database "recommendations" --force --verbose
    ```
- with docker container on ubuntu 18.04
    ```
    docker run --interactive --tty --rm \
        -p 7480:7474 -p 7680:7687 \
        -v /home/$USER/development/data/neo4jdb-movie-bk/data:/data \
        -v /home/$USER/development/data/neo4jdb-movie-bk/backups:/backups \
        --user=$(id -u):$(id -g) \
        neo4j:4.0.7 \
    neo4j-admin load --from=/backups/recommendations-40.dump --database="neo4j" --force
    ```
  -  note the container is build with 
    ```
    docker run -d \
            --name neo4jdb-movie-bk \
            -v /home/$USER/development/data/neo4jdb-movie-bk/data:/data \
            -v /home/$USER/development/data/neo4jdb-movie-bk/logs:/logs \
            -v /home/$USER/development/data/neo4jdb-movie-bk/import:/var/lib/neo4j/import \
            -v /home/$USER/development/data/neo4jdb-movie-bk/plugins:/plugins \
            -v /home/$USER/development/data/neo4jdb-movie-bk/backups:/backups \
            -p 7478:7474 -p 7678:7687 \
            --user=$(id -u):$(id -g) \
            --env NEO4J_AUTH=<xxxx/xxxxx> \
            neo4j:4.0.7
    ```
 
The log is shown as below:  
```
>>.\bin\neo4j-admin load --from data\recommendations-40.dump --database "recommendations" --force --verbose
org.neo4j.cli.CommandFailedException: Not a valid Neo4j archive: data\recommendations-40.dump
        at org.neo4j.commandline.dbms.LoadCommand.load(LoadCommand.java:189)
        at org.neo4j.commandline.dbms.LoadCommand.loadDump(LoadCommand.java:119)
        at org.neo4j.commandline.dbms.LoadCommand.execute(LoadCommand.java:91)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:59)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
        at picocli.CommandLine.execute(CommandLine.java:1864)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:77)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:58)
Caused by: org.neo4j.dbms.archive.IncorrectFormat: data\recommendations-40.dump
        at org.neo4j.dbms.archive.Loader.openArchiveIn(Loader.java:191)
        at org.neo4j.dbms.archive.Loader.load(Loader.java:74)
        at org.neo4j.commandline.dbms.LoadCommand.load(LoadCommand.java:165)
        ... 12 more
Caused by: java.io.IOException: Decompression error: Unknown frame descriptor
        at com.github.luben.zstd.ZstdInputStream.readInternal(ZstdInputStream.java:147)
        at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:107)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.neo4j.dbms.archive.CompressionFormat$2.decompress(CompressionFormat.java:79)
        at org.neo4j.dbms.archive.CompressionFormat.decompress(CompressionFormat.java:148)
        at org.neo4j.dbms.archive.CompressionFormat.decompress(CompressionFormat.java:125)
        at org.neo4j.dbms.archive.Loader.openArchiveIn(Loader.java:175)
        ... 14 more
        Suppressed: java.util.zip.ZipException: Not in GZIP format
                at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
                at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
                at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
                at org.neo4j.dbms.archive.CompressionFormat$1.decompress(CompressionFormat.java:52)
                at org.neo4j.dbms.archive.CompressionFormat.decompress(CompressionFormat.java:148)
                at org.neo4j.dbms.archive.CompressionFormat.decompress(CompressionFormat.java:132)
                ... 15 more
```

**Comment by exaptations** [comment]
See https://neo4j.com/docs/getting-started/appendix/example-data/

Specifically:

Import the file using the ./bin/neo4j-admin database load --overwrite-destination true --from-stdin <dbname> < file.dump command.

If running in docker then this will also help:

https://serverfault.com/questions/835092/how-do-you-perform-a-dump-of-a-neo4j-database-within-a-docker-container
